import os
import pandas as pd
import matplotlib.pyplot as plt
from jinja2 import Template
from config import REPORTS_DIR
from utils import setup_logger

logger = setup_logger("Reporter")

def generate_csv_report(df, filename="market_report.csv"):
    """Saves the DataFrame to a CSV file."""
    try:
        path = os.path.join(REPORTS_DIR, filename)
        df.to_csv(path, index=False)
        logger.info(f"CSV report generated at {path}")
    except Exception as e:
        logger.error(f"Error generating CSV report: {e}")

def generate_chart(df, ticker, filename):
    """Generates a price and moving average chart."""
    try:
        plt.figure(figsize=(10, 5))
        plt.plot(df['Date'], df['Close'], label='Close Price')
        plt.plot(df['Date'], df['MA_5'], label='5-Day MA', linestyle='--')
        plt.title(f"{ticker} Recent Price Trend")
        plt.xlabel("Date")
        plt.ylabel("Price")
        plt.legend()
        plt.xticks(rotation=45)
        plt.tight_layout()
        
        path = os.path.join(REPORTS_DIR, filename)
        plt.savefig(path)
        plt.close()
        return filename
    except Exception as e:
        logger.error(f"Error generating chart for {ticker}: {e}")
        return None

def generate_html_report(df, filename="market_summary.html"):
    """Generates an HTML summary report."""
    try:
        # Basic Summary Stats
        summary_stats = df.groupby('Ticker')[['Close', 'Daily_Return', 'Volatility']].agg(['mean', 'max', 'min']).round(2)
        
        # Generate Charts for each ticker
        charts = []
        unique_tickers = df['Ticker'].unique()
        for ticker in unique_tickers:
            ticker_df = df[df['Ticker'] == ticker].tail(30) # Last 30 days for chart
            chart_filename = f"{ticker}_chart.png"
            if generate_chart(ticker_df, ticker, chart_filename):
                charts.append({'ticker': ticker, 'image': chart_filename})

        # HTML Template
        template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>MarketPulse Daily Report</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #333; }
                table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #f2f2f2; }
                .chart-container { display: flex; flex-wrap: wrap; gap: 20px; }
                .chart { border: 1px solid #ccc; padding: 10px; border-radius: 5px; }
                img { max-width: 100%; height: auto; }
            </style>
        </head>
        <body>
            <h1>MarketPulse Daily Report</h1>
            
            <h2>Market Summary</h2>
            {{ summary_table }}
            
            <h2>Price Trends (Last 30 Days)</h2>
            <div class="chart-container">
                {% for chart in charts %}
                <div class="chart">
                    <h3>{{ chart.ticker }}</h3>
                    <img src="{{ chart.image }}" alt="{{ chart.ticker }} Chart">
                </div>
                {% endfor %}
            </div>
            
            <p>Generated by MarketPulse</p>
        </body>
        </html>
        """
        
        template = Template(template_str)
        html_content = template.render(
            summary_table=summary_stats.to_html(classes='table'),
            charts=charts
        )
        
        path = os.path.join(REPORTS_DIR, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        logger.info(f"HTML report generated at {path}")
        
    except Exception as e:
        logger.error(f"Error generating HTML report: {e}")
